### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Linchenguang** [MichalBusta/E2E-MLT#1]
Hello, MichalBusta
I tried to download the model, but I got the following error:
```
Forbidden
You don't have permission to access /public_datasets/SyntText/e2e-mlt.h5 on this server.
Apache/2.4.25 (Debian) Server at ptak.felk.cvut.cz Port 80
```

**Comment by MichalBusta** [comment]
should be ok now.

**Comment by Linchenguang** [comment]
It is OK now, very thanks!

**Comment by mohammed-Emad** [comment]
Is the server down?
It's the same problem

**Comment by MichalBusta** [comment]
No - server is running but the access rules changed (probably because of some migration - sorry, can not help)

**Comment by MichalBusta** [comment]
@mohammed-Emad : should be fixed now (I was kidding - I still do have access to a server)

**Comment by mohammed-Emad** [comment]
It hangs sometimes, but I was able to download it..
Thank you,
