### ISSUE TITLE
how to train English scene text alone?

### ISSUE THREAD

**Issue by zkself** [MichalBusta/E2E-MLT#13]
@MichalBusta  
I appreciate your nice work!  
i am new to scene text detection&recognition,which is part of my feature work.the procedure of training english scene text alone with my dataset.
could you please teach me how to train english scene text model with my dataset?

**Comment by zkself** [comment]
@MichalBusta  after read the closed issues of this work,i have some ideas of my training procedure.
1.arrange my dataset to suit the format.
2. use  train_ocr.py
is that right?
by the way,i use a subset of coco-text dataset.
and  how to arrange the data? i think it's  key procedure of training.
i am sorry for my naive questions and my bad english.

**Comment by MichalBusta** [comment]
> @MichalBusta after read the closed issues of this work,i have some ideas of my training procedure.
> 1.arrange my dataset to suit the format.
> 2. use train_ocr.py

Depends: if you want to use just OCR module, than use train_ocr.py, for full pipeline, use train.py

> is that right?
> by the way,i use a subset of coco-text dataset.

it is ok, but be careful - the coco-text is quite noisy  

> and how to arrange the data? i think it's key procedure of training.

you are right - most mistakes is just because of feeding bad data.  
see sample_train_data folder for correct data format.

**Comment by zkself** [comment]
@MichalBusta 
thanks for your advice!
Your answer proves my guess about the usage of train.py  and train_ocr.py.
after read your source code,i found that ocr just represent recognition moudle……
coco-text is so noisy that the during past two days, i merely cleaned and arranged the data……
