### ISSUE TITLE
loss always -2.00

### ISSUE THREAD

**Issue by WasFly** [MichalBusta/E2E-MLT#18]
When I train my own dataset, the values of ·loss· and seg_loss· are always equal -2.00. Other values are 0. Is there a problem? ,  I have not changed anything ,excep data set and batch_size(32), and train start from scratch

**Comment by MichalBusta** [comment]
one of the most parameters is input_size (size of the crops fed to 
network) - bigger=better.

  - you can use debug option of the script to see the data you are 
feeding. (the situation (probably) is, that you are feeding "empty data" 
- size of the text is too big or too small compared to input_size ... )

**Comment by WasFly** [comment]
I can confirm that it is not empty data, how to judge whether the text is too big or too small, i use Randomly generate 25-65 size characters in 1000X800 pictures

**Comment by WasFly** [comment]
Yes, my problem, sorry.
