### ISSUE TITLE
Error when running demo.py

### ISSUE THREAD

**Issue by DreadPiratePsyopus** [MichalBusta/E2E-MLT#21]
Hello @MichalBusta 
I have  a problem running demo.py
Apparently I cannot import get_boxes. The WrapCTC Loss was installed without a problem apparently, however this is the error I am getting..

make: Entering directory '/home/caffe/E2E-MLT/nms'
g++ -o adaptor.so -I include  -std=c++11 -O3 -I/home/caffe/anaconda3/envs/pytorch36/include/python3.6m -I/home/caffe/anaconda3/envs/pytorch36/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe  -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/caffe/anaconda3/envs/pytorch36/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/caffe/anaconda3/envs/pytorch36/lib -lpython3.6m -lpthread -ldl  -lutil -lrt -lm  -Xlinker -export-dynamic adaptor.cpp include/clipper/clipper.cpp --shared -fPIC
g++: error: unrecognized command line option ‘-fno-plt’
Makefile:10: recipe for target 'adaptor.so' failed
make: *** [adaptor.so] Error 1
make: Leaving directory '/home/caffe/E2E-MLT/nms'
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from nms import get_boxes
  File "/home/caffe/E2E-MLT/nms/__init__.py", line 8, in <module>
    raise RuntimeError('Cannot compile nms: {}'.format(BASE_DIR))
RuntimeError: Cannot compile nms: /home/caffe/E2E-MLT/nms

Any idea? Thanks in advance for your help.

**Comment by MichalBusta** [comment]
Your python has been probably compiled  with newer version g++: 
 - see python3-config --cflags

**Comment by DreadPiratePsyopus** [comment]
Hello @MichalBusta ,

The output result I got is the following:

-I/home/user1/anaconda3/envs/pytorch36/include/python3.6m -I/home/user1/anaconda3/envs/pytorch36/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe  -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall

Any specific version of g++ you used to compile?

Thanks in advance.

**Comment by MichalBusta** [comment]
Hi,

On 04/02/2019 15:06, DreadPiratePsyopus wrote:
>
> Hello @MichalBusta <https://github.com/MichalBusta> ,
>
> The output result I got is the following:
>
> -I/home/user1/anaconda3/envs/pytorch36/include/python3.6m 
> -I/home/user1/anaconda3/envs/pytorch36/include/python3.6m 
> -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell 
> -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe 
> -fdebug-prefix-map==/usr/local/src/conda/- 
> -fdebug-prefix-map==/usr/local/src/conda-prefix -fuse-linker-plugin 
> -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall
>
you can see, that your python (at /home/user1/anaconda3/envs/pytorch36) 
was compiled with compiler which supports -fno-plt

> Any specific version of g++ you used to compile?
>
I'm using g++ (7.3.0 and 6.3.0), (key is to use same compiler used for 
building python)

**Comment by DreadPiratePsyopus** [comment]
@MichalBusta ,
Thanks, I updated my gcc version and the code runs smoothly.
