### ISSUE TITLE
process_boxes() bug: does not iterate over all samples in the batch

### ISSUE THREAD

**Issue by mattroos** [MichalBusta/E2E-MLT#22]
There appears to be a bug in the process_boxes() function in train.py.

Line 70 should be:
```
 for bid in range(iou_pred.size(0)):
```
not
```
 for bid in range(iou_pred[0].size(0)):
```
In the main function of train.py, iou_pred[0] is passed to process_boxes(), not iou_pred. As written, it will not iterate over all samples in the batch, but over the length of the second dimension of iou_pred[0] (which is 1, the number of image color channel, blank/white in this case).

**Comment by MichalBusta** [comment]
sure, thanks!
