### ISSUE TITLE
Can't find script identification model

### ISSUE THREAD

**Issue by alwc** [MichalBusta/E2E-MLT#3]
1. It seems the current implementation of the E2E model only output "word transcription". Are you planning to release the part that output the "script identification"?

2. There are 3 outputs from the `ocr_image`: `det_text`, `conf`, and `dec_s`. I know what `det_text` is and I think `conf` means confidence, but how about `dec_s`?

Here is a partial log for the output of `ocr_image` function:

```python
conf: [[ 0 87]] dec_s: [[87]]
conf: [[ 0 69]] dec_s: [[63 69]]
conf: [[ 0 47]] dec_s: [[47]]
conf: [[ 0 48]] dec_s: [[47 48]]
conf: [[ 4 47]] dec_s: [[46 47]]
conf: [[ 4 95]] dec_s: [[94 95]]
conf: [[ 3 39]] dec_s: [[38 39]]
conf: [[ 4 55]] dec_s: [[54 55]]
conf: [[ 0 63]] dec_s: [[55 63]]
conf: [[ 0 71]] dec_s: [[70 71]]
conf: [[ 3 47]] dec_s: [[ 9 46 47]]
...
```

For `conf`, what does the single digit at index 0 represent? The double digit at index 1 is the confidence in range [0,100] right? For `dec_s`, I'm not sure how to interpret the numbers. Do you mind explaining it in depth?

Thank you for releasing the code btw!

**Comment by MichalBusta** [comment]
Hi Alex,

On 08/11/2018 04:41, Alex Lee wrote:
>
> 1.
>
>     It seems the current implementation of the E2E model only output
>     "word transcription". Are you planning to release the part that
>     output the "script identification"?
>
The paper status is not up to date. In new version we are doing script 
identification by OCR. However, I think we can release also the old code 
(http://rrc.cvc.uab.es/?ch=8&com=evaluation&task=2 - CNN based method 7).
>
> 1.
>
>
> 2.
>
>     There are 3 outputs from the |ocr_image|: |det_text|, |conf|, and
>     |dec_s|. I know what |det_text| is and I think |conf| means
>     confidence, but how about |dec_s|?
>
the dec_s (meaning decoding splits) is used for competition mode. The 
OCR knows spaces/punctuation so depending on evaluation protocol you can 
split proposals into fine "word level" boxes, even if the proposal 
covers more words. (so it is start and end position of the word) - can 
be done more precise.
>
> 1.
>
>
> Here is a partial log for the output of |ocr_image| function:
>
> conf: [[0  87]] dec_s: [[87]]
> conf: [[0  69]] dec_s: [[63  69]]
> conf: [[0  47]] dec_s: [[47]]
> conf: [[0  48]] dec_s: [[47  48]]
> conf: [[4  47]] dec_s: [[46  47]]
> conf: [[4  95]] dec_s: [[94  95]]
> conf: [[3  39]] dec_s: [[38  39]]
> conf: [[4  55]] dec_s: [[54  55]]
> conf: [[0  63]] dec_s: [[55  63]]
> conf: [[0  71]] dec_s: [[70  71]]
> conf: [[3  47]] dec_s: [[9  46  47]]
> ...
>
> For |conf|, what does the single digit at index 0 represent?
>
bad variable names - I'll do some code clean up. It should be indices  
start of the sequence/end of the sequence - probably not used anywhere.

**Comment by alwc** [comment]
Fantastic, thanks @MichalBusta !
