### ISSUE TITLE
bad image

### ISSUE THREAD

**Issue by colorful101** [MichalBusta/E2E-MLT#30]
hello,i'm sorry to bother you
when i run the train_ocr.py, it always show the bad image message,
![搜狗截图20190428222431](https://user-images.githubusercontent.com/32519597/56865782-6cd7b480-6a04-11e9-8ca3-70e5eb2481d4.png)
the validation dataset i used is part of ic15 test word images,could you please tell me why this codition happens?
thanks a lot!!!

**Comment by colorful101** [comment]
@MichalBusta

**Comment by MichalBusta** [comment]
https://github.com/MichalBusta/E2E-MLT/blob/1fb74eab8411185261d59ed2467fa59e4bd95530/ocr_test_utils.py#L140

you can add:
 import sys, traceback
 traceback.print_exc(file=sys.stdout)
after 'except:' 

to see what is going on

**Comment by colorful101** [comment]
Thank you so much for your reply,it seems that in ocr_test_utils.py
![1](https://user-images.githubusercontent.com/32519597/56873003-98d55300-6a61-11e9-8c83-a984a9b57dab.png)
this fuction needs four outputs  but just unpack three,when i add one output 
det_text, conf, dec_s, _=print_seq_ext()
the problem solves!
thanks you ~

**Comment by colorful101** [comment]
besides, i have one questions to ask for your help~
can i just use the ocr model to train a seperate word recognition model(just to achieve recognition task).if i can do like this,how large dataset should i have?(i just want to test on icdar2015 word recognition dataset )
thank you ! @MichalBusta

**Comment by colorful101** [comment]
Could you please give me some advice?Thanks a lot~

**Comment by MichalBusta** [comment]
Hi,

On 29/04/2019 06:08, cooooor wrote:
>
> besides, i have one questions to ask for your help~
> can i just use the ocr model to train a seperate word recognition 
> model(just to achieve recognition task).
>
sure, there is 
https://github.com/MichalBusta/E2E-MLT/blob/master/train_ocr.py script 
just for training ocr module.
>
> if i can do like this,how large dataset should i have?(i just want to 
> test on icdar2015 word recognition dataset )
>
hard to say - depends on data - (sythetic images - VGG group have been 
using *9 million images*covering*90k English words* for ICDAR 2013 
dataset, real images ~ 100000 from icdar2015 and icdar2017 MLT will give 
you quite good baseline ... )

**Comment by colorful101** [comment]
By the way,Does the 100000 images need to only cover English words ? @MichalBusta

**Comment by colorful101** [comment]
hello，when i use the dataset from IC15、IC17MLT&IC19MLT(only use the latin words，about 70000word images)，and only run the train_ocr.py，but the accuracy on ic15 test word dataset can just achieve 56.3% accuracy ，the batchsize i used equals to 4，could you please give me some advice why the accuracy is so low，and what should i do to improve it ?
![4](https://user-images.githubusercontent.com/32519597/57122896-2a222d80-6db2-11e9-832e-3722562a5b5b.png)

Thanks a lot~

**Comment by MichalBusta** [comment]
No easy answer sorry :) 
 - so low accuracy compared to who ( Baidu IDL, Alibaba PAI, Baidu VIS )? 
what can help:
- data, data, data ... (google PhotoOCR ~= 3mil manually annotated images, you should expect log scale dependency)
- language modeling 
- more complicated model(s) (this project focus on real-time text detection), so you can go to seq-to-seq models ... good starer paper: http://openaccess.thecvf.com/content_cvpr_2016/html/Lee_Recursive_Recurrent_Nets_CVPR_2016_paper.html - quite old, but still good

**Comment by colorful101** [comment]
ok，i will try.thanks so much for your reply~

**Comment by alwc** [comment]
@MichalBusta I also have some questions regarding your text recognition model.

1/ For latin languages, did you train your text recognition models with single word images only (i.e. no text lines)? 

2/ How many images did you train your text recognition model with?

3/ Your text recognition model seems to use a ResNet like structure. Since this project focus on real-time, have you tried to train your text recognition model with a MobileNet backbone?

**Comment by MichalBusta** [comment]
pondělí 8. července 2019 Alex Lee <notifications@github.com> napsal(a):

> @MichalBusta <https://github.com/MichalBusta> I also have some questions
> regarding your text recognition model.
>
> 1/ For latin languages, did you train your text recognition models with
> single word images only (i.e. no text lines)?
>
most of the images in used datasets are word level, some of the generated
images are line-level

> 2/ How many images did you train your text recognition model with?
>
sorry I'm travelling so I can not give you exact number but it will be
about 500k

> 3/ Your text recognition model seems to use a ResNet like structure.
>
no - text detection is resnet-like. recognition is plain vgg style.

> Since this project focus on real-time, have you tried to train your text
> recognition model with a MobileNet backbone?
>
no - it is about the hardware - we were targeting  low-end GPUs.

**Comment by alwc** [comment]
Thanks @MichalBusta ! One more thing, for the 500k images, it consists of an equal share between Arabic, Bangla, Chinese, Japanese, Korean and Latin (i.e. ~80k images for each script)?

**Comment by MichalBusta** [comment]
+/- : we have used more real latin and chinese data since there are a
datasets. For synth equal split.

středa 10. července 2019 Alex Lee <notifications@github.com> napsal(a):
