### ISSUE TITLE
What does label named ### mean?

### ISSUE THREAD

**Issue by kei6** [MichalBusta/E2E-MLT#34]
Dear @MichalBusta,
Some lines in ground-truth
522,145,535,144,537,160,523,161,**###**
535,141,598,137,599,155,537,159,BUTTER
608,136,649,133,650,150,609,153,TRUE
649,132,723,125,724,143,650,150,**###**

What does ### mean? What is its mean for training?

Thanks,

**Comment by victoic** [comment]
It means "Do notcare", a sign for the label to be ignored. It is a pattern from the ICDAR 2015 dataset, you can read more about that specific dataset here: [http://rrc.cvc.uab.es/?ch=4&com=tasks](url)

**Comment by MichalBusta** [comment]
On Fri, 17 May 2019 01:56 Kei_Cin, <notifications@github.com> wrote:

> Dear @MichalBusta <https://github.com/MichalBusta>,
> Some lines in ground-truth
> 522,145,535,144,537,160,523,161,*###*
> 535,141,598,137,599,155,537,159,BUTTER
> 608,136,649,133,650,150,609,153,TRUE
> 649,132,723,125,724,143,650,150,*###*
>
> What does ### mean? What is its mean for training?
>
Do not care - for training we mask those regions out

Thanks,

**Comment by kei6** [comment]
Thanks, I'm clear! I'll close this issue!
