### ISSUE TITLE
Detect rectangle box only

### ISSUE THREAD

**Issue by kei6** [MichalBusta/E2E-MLT#35]
Hi @MichalBusta,
First of all, thanks for your great work!
My training dataset has only samples with rectangle boxes! After 200 epoch of training, the model can predict liked below image:
![Annotation 2019-05-23 142022](https://user-images.githubusercontent.com/45931733/58233321-f6f60d00-7d65-11e9-8eed-80cbdbc968ac.png)
Because of wrong `angle` detecting, that leads to wrong OCR result!

Then I think about a model with no angle (or `unchanged angle`) to predict rectangle boxes only.
I've known that your model with angle is really awesome, but in my case to predict rectangle boxes only.
How can I do it?

Thanks a lot!

**Comment by MichalBusta** [comment]
a lot of options
 - do not regress angle
 - disable the rotation aug. In training
 - .....
Whatever works for you
