### ISSUE TITLE
Need help to understand pts=np.roll(pts, 2)

### ISSUE THREAD

**Issue by kei6** [MichalBusta/E2E-MLT#36]
I'm going deeper to your repo and I cannot understand this below code:
https://github.com/MichalBusta/E2E-MLT/blob/28583581fb17b6e83bc8dc8c84b6bc7fb4957341/data_gen.py#L122-L123

I've checked some examples with this and find out that will shift an array liked:
`[1224. 2041. 1537. 2041. 1537. 2134. 1224. 2134.]`
into:
`[1224. 2134. 1224. 2041. 1537. 2041. 1537. 2134.]`

I know how numpy.roll function works, but I don't understand why you did it only for ICDAR dataset.
Can you help to explain this?
Thanks,

**Comment by MichalBusta** [comment]
we normalized all data to common format, ours gt start with bottom left.

neděle 2. června 2019 Kei_Cin <notifications@github.com> napsal(a):

**Comment by kei6** [comment]
Thanks for this quick explanation!
It is really important information if anyone wants to train your network with their own data, they need to make sure the data format start with bottom left.
