### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by shin7** [MichalBusta/E2E-MLT#37]
Hello, I have met a problem when training the model as follow:

**RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 983.69 MiB total capacity; 209.53 MiB already allocated; 69.56 MiB free; 6.47 MiB cached)**

could you give me any solutions?
Thank you!

**Comment by kei6** [comment]
It seems your device is not strong enough to train this model. 1G of GPU is really small.
I'm using 16Gb GPU and this model uses its all.
