### ISSUE TITLE
Vertical text recognition

### ISSUE THREAD

**Issue by kei6** [MichalBusta/E2E-MLT#38]
Dear @MichalBusta,

[This label](https://github.com/MichalBusta/E2E-MLT/blob/master/sample_train_data/MLT/done/gt_img_5407.txt) is confusing me. Those are Japanese vertical text and I didn't find any algorithm in your works can solve vertical text-line recognition.

![img_5407](https://user-images.githubusercontent.com/45931733/58792069-a8762780-861d-11e9-86bb-5b312a92b8bf.jpg)

Sorry for my lack of knowledge if your works can solve it, I've just worked in OCR field for a year.
 **Can you show me which part of your works solve vertical text-line??**
That is really interesting if my next works can contribute to your works a vertical text recognition module.
Thanks,

**Comment by MichalBusta** [comment]
we train network to predict reading direction. OCR module do not care if
chars are rotated. if you train on same data, model will fit them.

Hope it helps. Michal

pondělí 3. června 2019 Kei_Cin <notifications@github.com> napsal(a):
