### ISSUE TITLE
score_map vs. training_masks

### ISSUE THREAD

**Issue by kei6** [MichalBusta/E2E-MLT#43]
Dear @MichalBusta,
I'm trying to understand the difference between score_map and training_masks, which are generated from: https://github.com/MichalBusta/E2E-MLT/blob/28583581fb17b6e83bc8dc8c84b6bc7fb4957341/data_gen.py#L555
Having some questions come in with me:
1. Which one is more important to train the model? (I checked and found that score_map always have all ground-truth boxes, but training_masks is not)
2. Why do you generate score_map and training_masks? (Because according to my work to understand your works, I think just score_map is enough. Pls help to fix if I have misunderstood, thanks!)
3. Why do you just add a box to training_masks if its text contains " ", according to this line of code: https://github.com/MichalBusta/E2E-MLT/blob/28583581fb17b6e83bc8dc8c84b6bc7fb4957341/data_gen.py#L478-L496
Hope to hear from you soon,
Thanks in advance,

**Comment by MichalBusta** [comment]
hi Kei,
train mask Is used to mask out regions from score map - mostly:
 - do not care regions
 - regions partially out of image
 - too small text

we do not learn on those masked out parts.

úterý 2. července 2019 Kei_Cin <notifications@github.com> napsal(a):

**Comment by kei6** [comment]
Thanks for this quick reply!
To be clear, the model learns from score_map, doesn't it?

**Comment by MichalBusta** [comment]
Yes, but only on parts given by train mask.

středa 3. července 2019 Kei_Cin <notifications@github.com> napsal(a):
