### ISSUE TITLE
Is it possible to use e2e-mlt weight file for android mobile???

### ISSUE THREAD

**Issue by a41888936** [MichalBusta/E2E-MLT#45]
I have a plan to make OCR app(on-device) for android mobile using my own training model.

I guess E2E-MLT is a multi-language OCR engine that shows the best performance so far.

Is there any way that I convert trained weight file on Android ???

**Comment by MichalBusta** [comment]
On Fri, 12 Jul 2019 01:12 leehochan, <notifications@github.com> wrote:

> I have a plan to make OCR app(on-device) for android mobile using my own
> training model.
>
> I guess E2E-MLT is a multi-language OCR engine that shows the best
> performance so far.
>
See the latest ICDAR MLT results - the winner of the competition uses
models ensemble. We just provide reasonable  solution to start with.

> Is there any way that I convert trained weight file on Android ???
>
Too wide (android is just OS?)question - no simple answer.

**Comment by a41888936** [comment]
Thanks!
