### ISSUE TITLE
A confidence value for evaluation?

### ISSUE THREAD

**Issue by shin7** [MichalBusta/E2E-MLT#56]
Thank for your great work!

for bid, box in enumerate(detections):      
      
        boxo = detectionso[bid]
        score = boxo[8]
        boxr = boxo[0:8].reshape(-1, 2)
        box_area = area( boxr.reshape(8) )

Is the `score` variable here, in eval.py, refer to a confidence value?
Thank you!

**Comment by MichalBusta** [comment]
Yes.

**Comment by MichalBusta** [comment]
the score is summation of all confidences merged during NMS, 
see: 
https://github.com/MichalBusta/E2E-MLT/blob/61df47f3aa5f3ce54633bb28e3c828d7d59afd68/nms/adaptor.cpp#L24 

if you want average value, you have to change code to: p.score / p.nr_polys

(but does not reflect anything - we are learning pixel probability with dice loss and for text detection for fully trained network, values are almost always 0 and 1 )

**Comment by shin7** [comment]
Thank you!
