### ISSUE TITLE
Character-level boxes

### ISSUE THREAD

**Issue by ThisIsIsaac** [MichalBusta/E2E-MLT#57]
The original SynthText dataset supports character-level bounding boxes. Does this implementation also support char-level boxes? If so, how can I enable it?

**Comment by MichalBusta** [comment]
Sorry, no character boxes has been generated.

**Comment by ThisIsIsaac** [comment]
If I were to try to add it, should I edit the post-processing, or is it due to the inherent network architecture?

**Comment by ThisIsIsaac** [comment]
@MichalBusta 
I am training CRAFT which requires character-level boxes (although weakly-supervised with word-level boxes is possible). What fonts, texts, and images did you use to generate the Korean Synthetic ML data you've linked? I am aming to produce the data you have produced, but with character-level boxes instead.

**Comment by MichalBusta** [comment]
> @MichalBusta
> I am training CRAFT which requires character-level boxes (although weakly-supervised with word-level boxes is possible). What fonts, texts, and images did you use to generate the Korean Synthetic ML data you've linked? I am aming to produce the data you have produced, but with character-level boxes instead.

Hi @ThisIsIsaac, 
the code for generation is linked in Readme: https://github.com/ankush-me/SynthText. 
if you want to generate also the character level GT, use the repository, and write to the author (Ankush Gupta) for full set of background images (it will be probably provided on condition, that you will share generated images with GT.)

All the best, Michal
