### ISSUE TITLE
Is englist scene text supported?

### ISSUE THREAD

**Issue by liutianling** [MichalBusta/E2E-MLT#58]
Your work is great, thanks for your sharing!
I wonder if englist scene test is supported?  Since the englisth is not in Latin, so i want to konw the englist scene test is supported or not?  The englist scene text can be located or recognized ?
I am sorry for my bad english. 
Thanks.

**Comment by MichalBusta** [comment]
Hi liutianling, I'm having trouble understand the question - what is 'englist scene'? 

If english, than yes: Latin (in meaning of latin alphabet)  ~= (english, spanish, franch, italian, german, czech), but the english is at least 50% of train set ....

**Comment by liutianling** [comment]
@MichalBusta 
Thanks very much for you reply. It is my fault for error writting english to englist。
Thanks.
