### ISSUE TITLE
Training_ocr all zeros

### ISSUE THREAD

**Issue by Linchenguang** [MichalBusta/E2E-MLT#6]
Hello, I want to retrain the model for Chinese only, however, when run `python train_ocr.py` the predicted label is all zeros, and the ctc loss is  up and down 

![default](https://user-images.githubusercontent.com/5471010/48655464-de710700-ea51-11e8-99ec-5c7eae3dd0f4.JPG)

have you ever encountered this problem before?  I also tried to change the learning rate, but there is nothing help.

**Comment by MichalBusta** [comment]
How many iterations?  (in early stages it is normal - the label 0 <padding> is most probable label)
learning rate = 0.0001, batch size = 256 - after 100 000 loss should go down. It takes while for optimizer to get some reasonable momentum.

**Comment by Linchenguang** [comment]
Very thanks for your quick reply, I will try it later! Thanks
