### ISSUE TITLE
How to evaluate E2E-MLT？

### ISSUE THREAD

**Issue by MiTeng0215** [MichalBusta/E2E-MLT#63]
In the binary classification task, I know the meaning of 'precision' and 'recall', but how do I calculate 'precision' and 'recall' in the E2E evaluation criteria? How to represent TP and FP?Such as the End-to-end evaluation on generic setting of ICDAR 2015 dataset.

**Comment by MichalBusta** [comment]
Hi, 
it is same like in binary classification: in ICDAR competition protocol, you have to pass detection threshold 0.5 (IoU) and if your transcription matches GT you get the cookie (TP). Everything else is FP. (with one exception- there are also "do not care regions") 

for details see https://rrc.cvc.uab.es/?ch=4&com=tasks and referenced papers.
