### ISSUE TITLE
The problem of "-ocr_feed_list" config

### ISSUE THREAD

**Issue by duxiangcheng** [MichalBusta/E2E-MLT#65]
In the train configurations, I noticed the option "-ocr_feed_list". What does this option do?

**Comment by duxiangcheng** [comment]
@MichalBusta  Please help me! thanks

**Comment by MichalBusta** [comment]
pointer to GT list of cropped words. 
 - see: https://github.com/MichalBusta/E2E-MLT/tree/master/sample_train_data/MLT_CROPS

**Comment by duxiangcheng** [comment]
@MichalBusta But the data in the repo are images along with their gt.  Where can I get the cropped images? During your training, what's the ratio of the two(-train_list and -ocr_feed_list)?

**Comment by MichalBusta** [comment]
Simply cut rotated rectangles from full GT images. 
additionally you can generate some synthetic data or use some already generated (https://www.robots.ox.ac.uk/~vgg/research/text/)
