### ISSUE TITLE
the problem about input_size

### ISSUE THREAD

**Issue by duxiangcheng** [MichalBusta/E2E-MLT#69]
Hi, Thanks for sharing the amazing code.
I notice that the input_size is 256 which is used in data_gen.py.  I know the function of the input_size is the size of the cut images. But why is the size is 256?

**Comment by MichalBusta** [comment]
Hi, it is just debug setting (to fit GPU on my notebook)
see: 
https://github.com/MichalBusta/E2E-MLT#training 
I would recommend to train with input_size 512
