### ISSUE TITLE
Weird bounding box results

### ISSUE THREAD

**Issue by alwc** [MichalBusta/E2E-MLT#8]
Today I've tested the model with a few images and I'm getting some weird results, there are 2 cases that I'll highlight:

1. Here are three OCR prediction results 

<img width="659" alt="latin_1" src="https://user-images.githubusercontent.com/1621953/48897498-36aa6d80-ee85-11e8-844a-febc692b115d.png">

<img width="725" alt="chinese_1" src="https://user-images.githubusercontent.com/1621953/48897574-65c0df00-ee85-11e8-9daa-992041c22d93.png">
<img width="383" alt="latin_3" src="https://user-images.githubusercontent.com/1621953/48897676-a28cd600-ee85-11e8-9471-368685313113.png">

Notice that some of the text recognition predictions include words/characters from the neighboring bounding boxes. For example, for the first image, you can see the bounding box that predicts `at $50000` contains only `$50000`, but it can still predict `at` for some reason. Is that a bug? 

2. For tiny sequence of characters, I'm getting some really weird bounding boxes

<img width="929" alt="latin_2" src="https://user-images.githubusercontent.com/1621953/48898032-a10fdd80-ee86-11e8-96b4-4d1ce33206ad.png">

Notice that for this particular image I didn't resize the image (i.e. `im_resized = im` in `demo.py`). Here is the input image if you are interested in reproducing the predictions: 
![table_with_tiny_numbers](https://user-images.githubusercontent.com/1621953/48898230-36ab6d00-ee87-11e8-9c3b-0670a70998e9.jpg)

**Comment by MichalBusta** [comment]
You are just testing on data which are out of the training distribution - no surprise ...

**Comment by alwc** [comment]
> You are just testing on data which are out of the training distribution - no surprise ...

I think that answers my question 2, which I agree with you, but how about question 1? It seems some results are recognizing words beyond its bounding box range (e.g. Recognizing `at $50000` when the bbox only contains $50000).

**Comment by MichalBusta** [comment]
Answer for Q1 can be: 
 - the proposal is expanded before ocr (line 80, ocr_utils:  target_gw = int(w * scale) + target_h )

**Comment by alwc** [comment]
Thanks @MichalBusta , I'll take a look and see if I could make any improvement for Q1.

**Comment by zhouyuangan** [comment]
Hi @alwc How do you solve this problem? Have you trained this model on your own dataset? How about your model's performance now? I met the same problem as yours, I need your help, please. Thank you.
